Update Approval_request.md
w3c/verifiable-credentials pull request #57
Opened 2024-04-03 23:53 UTC by decentralgabe

I believe all that is missing is the resolution which will come next week.

2024-04-04 06:33 UTC, iherman commented
Looks good to me, but I have an editorial comment. The reason the file is in Markdown is that the official transition request is done via GitHub, i.e., in Markdown. However, your changes are like:

```markdown
[https://github.com/w3ctag/design-reviews/issues/889]()
```

which is not o.k. Can you simply remove the unnecessary parenthesis from all these?

2024-04-04 07:39 UTC, iherman commented
(Adding @msporny here, because he knows the more precise text and references.)

I try to anticipate the questions the reviewers may have: they usually ask whether the media types we are talking about have been registered or not; in general, WG-s are supposed to start the procedure when entering CR. Our case is special, because we hit the multiple suffix problem, and we can not yet submit those media types (if at all).

I would think that, at the end of the request, we should add an "Additional Comment" section where we describe the current situation.

For reference, see 
- questions coming on the VCDM CR transition: https://github.com/w3c/transitions/issues/587#issuecomment-1900562225
- detailed answer of @msporny which closed that line of question: https://github.com/w3c/transitions/issues/587#issuecomment-1902276576

We _could_ simply refer back to @msporny's answer, but things have evolved since then...

@msporny could you help out with this?

2024-04-08 07:35 UTC, iherman commented
@decentralgabe @msporny I have added a note on the media type issue at the end of the request. Please review.

2024-04-09 14:02 UTC, TallTed requested changes
Language tweaks for clarity

2024-04-09 14:02 UTC, TallTed commented on admin/CR-jose-cose-2024/Approval_request.md
> +by the VC Working Group on the best approach to be taken by the Working Group; whatever will be decided for the VC Data Model will also affect the JOSE-COSE specification, too.
```suggestion
Unfortunately, the discussion at IETF 119 did not result in a clear decision. There is now a [separate discussion](https://github.com/w3c/vc-data-model/issues/1462) 
by the VC Working Group about their best approach; whatever they decide for the VC Data Model will likely affect the JOSE-COSE specification, too.
```

2024-04-09 14:21 UTC, iherman approved these changes

2024-04-09 15:45 UTC, TallTed approved these changes

2024-04-09 16:52 UTC, brentzundel approved these changes

2024-04-10 06:19 UTC, merged